### ISSUE TITLE
Getting CSS error

### ISSUE THREAD

**Issue by andreyluiz** [Storytel/react-redux-spinner#13]
I am getting the following error:

```
/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-redux-spinner/dist/nprogress.css:2
#nprogress {
^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/andrey/Projects/Datarisk/app-frontend/node_modules/b
abel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/andrey/Projects/Datarisk/app-frontend/node_modules/react-redux-spinner/dist/index.js:8:1)
error Command failed with exit code 1.
```

I have set up everything correctly. I use webpack and I have a loader for CSS.

What are my options?

**Comment by enheit** [comment]
I had the same issue, but I fixed it by adding CSS loader

`            {
                test: /\.css$/,
                loaders: ['style-loader', 'css-loader?sourceMap']
            },`

**Comment by noseglid** [comment]
It looks like it's not being run thorugh the CSS loader. Do you have a loader setup  as @enheit described?

**Comment by andreyluiz** [comment]
Yeah, as @noseglid said, I have the css loader, but still the error persists.

**Comment by noseglid** [comment]
Could you share your webpack config?
